# Generated by Django 5.2 on 2026-01-15 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pv/', verbose_name='Fichier PV')),
                ('filiere', models.CharField(max_length=200, verbose_name='Filière')),
                ('niveau', models.IntegerField(verbose_name="Niveau d'étude")),
                ('semestre', models.CharField(max_length=10, verbose_name='Semestre')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('formation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de formation')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
            ],
            options={
                'verbose_name': 'Procès-Verbal',
                'verbose_name_plural': 'Procès-Verbaux',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='N°')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule')),
                ('nom_prenom', models.CharField(max_length=300, verbose_name='Nom & Prénom')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne générale')),
                ('credits_acquis', models.IntegerField(default=0, verbose_name='Crédits acquis')),
                ('decision_generale', models.CharField(choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], max_length=10, verbose_name='Décision générale')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='pv.procesverbal')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['numero'],
                'unique_together': {('pv', 'matricule')},
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code UE')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('ordre', models.IntegerField(verbose_name="Ordre d'affichage")),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='pv.procesverbal')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
                'ordering': ['ordre'],
                'unique_together': {('pv', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code ECUE')),
                ('intitule', models.CharField(max_length=300, verbose_name='Intitulé')),
                ('ordre', models.IntegerField(verbose_name="Ordre d'affichage")),
                ('credits', models.IntegerField(default=3, verbose_name='Nombre de crédits')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='pv.ue')),
            ],
            options={
                'verbose_name': "Élément Constitutif d'UE",
                'verbose_name_plural': "Éléments Constitutifs d'UE",
                'ordering': ['ordre'],
                'unique_together': {('ue', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Contrôle Continu')),
                ('examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Examen')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne')),
                ('credit_attribue', models.IntegerField(default=0, verbose_name='Crédit attribué')),
                ('decision', models.CharField(choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], max_length=10, verbose_name='Décision')),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pv.ecue')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pv.etudiant')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['ecue__ordre'],
                'unique_together': {('etudiant', 'ecue')},
            },
        ),
        migrations.CreateModel(
            name='SyntheseUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_ue', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne UE')),
                ('credits_attribues', models.IntegerField(default=0, verbose_name='Crédits attribués')),
                ('decision', models.CharField(choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], max_length=10, verbose_name='Décision')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses_ue', to='pv.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses', to='pv.ue')),
            ],
            options={
                'verbose_name': 'Synthèse UE',
                'verbose_name_plural': 'Synthèses UE',
                'ordering': ['ue__ordre'],
                'unique_together': {('etudiant', 'ue')},
            },
        ),
    ]
