# Generated by Django 5.2 on 2026-01-17 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='credit_attribue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Crédit attribué'),
        ),
        migrations.AlterField(
            model_name='note',
            name='decision',
            field=models.CharField(blank=True, choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], max_length=10, null=True, verbose_name='Décision'),
        ),
        migrations.AlterField(
            model_name='note',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne'),
        ),
        migrations.AlterField(
            model_name='syntheseue',
            name='credits_attribues',
            field=models.IntegerField(blank=True, null=True, verbose_name='Crédits attribués'),
        ),
        migrations.AlterField(
            model_name='syntheseue',
            name='decision',
            field=models.CharField(blank=True, choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], max_length=10, null=True, verbose_name='Décision'),
        ),
        migrations.AlterField(
            model_name='syntheseue',
            name='moyenne_ue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne UE'),
        ),
    ]
