# Generated by Django 5.2 on 2026-01-17 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0002_alter_note_credit_attribue_alter_note_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='credits_acquis',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Crédits acquis'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='decision_generale',
            field=models.CharField(blank=True, choices=[('V', 'Validé'), ('NV', 'Non Validé'), ('VC', 'Validé par Compensation')], default=None, max_length=10, null=True, verbose_name='Décision générale'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='moyenne_generale',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne générale'),
        ),
    ]
