# Generated by Django 5.2 on 2026-01-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0003_alter_etudiant_credits_acquis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesverbal',
            options={'ordering': ['-date_import', 'fichier_parent', 'nom_feuille'], 'verbose_name': 'Procès-Verbal', 'verbose_name_plural': 'Procès-Verbaux'},
        ),
        migrations.AddField(
            model_name='procesverbal',
            name='fichier_parent',
            field=models.CharField(blank=True, help_text='Nom du fichier Excel parent pour regroupement', max_length=255, null=True, verbose_name='Fichier parent'),
        ),
        migrations.AddField(
            model_name='procesverbal',
            name='nom_feuille',
            field=models.CharField(blank=True, help_text='Nom de la feuille Excel source (si fichier multi-feuilles)', max_length=100, null=True, verbose_name='Nom de la feuille Excel'),
        ),
    ]
