# Generated by Django 5.2 on 2026-01-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0004_alter_procesverbal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesverbal',
            options={'ordering': ['-date_import'], 'verbose_name': 'Procès-Verbal', 'verbose_name_plural': 'Procès-Verbaux'},
        ),
        migrations.RemoveField(
            model_name='procesverbal',
            name='fichier_parent',
        ),
        migrations.RemoveField(
            model_name='procesverbal',
            name='nom_feuille',
        ),
    ]
